//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPingPongCSClient.WSPingPongCSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPingPongCSService.WSPingPongCSServiceSoap")]
    public interface WSPingPongCSServiceSoap {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname ball_ aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ball_In", ReplyAction="*")]
        WSPingPongCSClient.WSPingPongCSService.Ball_InResponse Ball_In(WSPingPongCSClient.WSPingPongCSService.Ball_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ball_In", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPingPongCSClient.WSPingPongCSService.Ball_InResponse> Ball_InAsync(WSPingPongCSClient.WSPingPongCSService.Ball_InRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname Ball_OutResult aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ball_Out", ReplyAction="*")]
        WSPingPongCSClient.WSPingPongCSService.Ball_OutResponse Ball_Out(WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ball_Out", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPingPongCSClient.WSPingPongCSService.Ball_OutResponse> Ball_OutAsync(WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ball_Check", ReplyAction="*")]
        bool Ball_Check();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ball_Check", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Ball_CheckAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ball_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ball_In", Namespace="http://tempuri.org/", Order=0)]
        public WSPingPongCSClient.WSPingPongCSService.Ball_InRequestBody Body;
        
        public Ball_InRequest() {
        }
        
        public Ball_InRequest(WSPingPongCSClient.WSPingPongCSService.Ball_InRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ball_InRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ball_;
        
        public Ball_InRequestBody() {
        }
        
        public Ball_InRequestBody(string ball_) {
            this.ball_ = ball_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ball_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ball_InResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSPingPongCSClient.WSPingPongCSService.Ball_InResponseBody Body;
        
        public Ball_InResponse() {
        }
        
        public Ball_InResponse(WSPingPongCSClient.WSPingPongCSService.Ball_InResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Ball_InResponseBody {
        
        public Ball_InResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ball_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ball_Out", Namespace="http://tempuri.org/", Order=0)]
        public WSPingPongCSClient.WSPingPongCSService.Ball_OutRequestBody Body;
        
        public Ball_OutRequest() {
        }
        
        public Ball_OutRequest(WSPingPongCSClient.WSPingPongCSService.Ball_OutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Ball_OutRequestBody {
        
        public Ball_OutRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ball_OutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ball_OutResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSPingPongCSClient.WSPingPongCSService.Ball_OutResponseBody Body;
        
        public Ball_OutResponse() {
        }
        
        public Ball_OutResponse(WSPingPongCSClient.WSPingPongCSService.Ball_OutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ball_OutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ball_OutResult;
        
        public Ball_OutResponseBody() {
        }
        
        public Ball_OutResponseBody(string Ball_OutResult) {
            this.Ball_OutResult = Ball_OutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPingPongCSServiceSoapChannel : WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPingPongCSServiceSoapClient : System.ServiceModel.ClientBase<WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap>, WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap {
        
        public WSPingPongCSServiceSoapClient() {
        }
        
        public WSPingPongCSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPingPongCSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPingPongCSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPingPongCSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPingPongCSClient.WSPingPongCSService.Ball_InResponse WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap.Ball_In(WSPingPongCSClient.WSPingPongCSService.Ball_InRequest request) {
            return base.Channel.Ball_In(request);
        }
        
        public void Ball_In(string ball_) {
            WSPingPongCSClient.WSPingPongCSService.Ball_InRequest inValue = new WSPingPongCSClient.WSPingPongCSService.Ball_InRequest();
            inValue.Body = new WSPingPongCSClient.WSPingPongCSService.Ball_InRequestBody();
            inValue.Body.ball_ = ball_;
            WSPingPongCSClient.WSPingPongCSService.Ball_InResponse retVal = ((WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap)(this)).Ball_In(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPingPongCSClient.WSPingPongCSService.Ball_InResponse> WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap.Ball_InAsync(WSPingPongCSClient.WSPingPongCSService.Ball_InRequest request) {
            return base.Channel.Ball_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPingPongCSClient.WSPingPongCSService.Ball_InResponse> Ball_InAsync(string ball_) {
            WSPingPongCSClient.WSPingPongCSService.Ball_InRequest inValue = new WSPingPongCSClient.WSPingPongCSService.Ball_InRequest();
            inValue.Body = new WSPingPongCSClient.WSPingPongCSService.Ball_InRequestBody();
            inValue.Body.ball_ = ball_;
            return ((WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap)(this)).Ball_InAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPingPongCSClient.WSPingPongCSService.Ball_OutResponse WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap.Ball_Out(WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest request) {
            return base.Channel.Ball_Out(request);
        }
        
        public string Ball_Out() {
            WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest inValue = new WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest();
            inValue.Body = new WSPingPongCSClient.WSPingPongCSService.Ball_OutRequestBody();
            WSPingPongCSClient.WSPingPongCSService.Ball_OutResponse retVal = ((WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap)(this)).Ball_Out(inValue);
            return retVal.Body.Ball_OutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPingPongCSClient.WSPingPongCSService.Ball_OutResponse> WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap.Ball_OutAsync(WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest request) {
            return base.Channel.Ball_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPingPongCSClient.WSPingPongCSService.Ball_OutResponse> Ball_OutAsync() {
            WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest inValue = new WSPingPongCSClient.WSPingPongCSService.Ball_OutRequest();
            inValue.Body = new WSPingPongCSClient.WSPingPongCSService.Ball_OutRequestBody();
            return ((WSPingPongCSClient.WSPingPongCSService.WSPingPongCSServiceSoap)(this)).Ball_OutAsync(inValue);
        }
        
        public bool Ball_Check() {
            return base.Channel.Ball_Check();
        }
        
        public System.Threading.Tasks.Task<bool> Ball_CheckAsync() {
            return base.Channel.Ball_CheckAsync();
        }
    }
}
