//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPingPongHost.PingPongServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PingPongServiceReference.IPingPongService")]
    public interface IPingPongService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPingPongService/Ball_In", ReplyAction="http://tempuri.org/IPingPongService/Ball_InResponse")]
        void Ball_In(string ball);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPingPongService/Ball_Out", ReplyAction="http://tempuri.org/IPingPongService/Ball_OutResponse")]
        string Ball_Out();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPingPongServiceChannel : WSPingPongHost.PingPongServiceReference.IPingPongService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingPongServiceClient : System.ServiceModel.ClientBase<WSPingPongHost.PingPongServiceReference.IPingPongService>, WSPingPongHost.PingPongServiceReference.IPingPongService {
        
        public PingPongServiceClient() {
        }
        
        public PingPongServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PingPongServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PingPongServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PingPongServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ball_In(string ball) {
            base.Channel.Ball_In(ball);
        }
        
        public string Ball_Out() {
            return base.Channel.Ball_Out();
        }
    }
}
